version: "3.3"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_ROOT_PASSWORD=
      - TZ=America/Los_Angeles
    volumes:
      - ./.db:/config
    ports:
      - 3307:3307
    restart: unless-stopped

  baseball:
    build:
      context: .
      dockerfile: Dockerfile
    image: baseball
    restart: unless-stopped
    volumes:
      - "./stuff:/app/stuff"
